### ISSUE TITLE
Amazon Music / Twitch don't work

### ISSUE THREAD

**Issue by Dudebaker** [tjhrulz/WebNowPlaying#11]
It seems that the Amazon Music and Twitch integration is broken - doesn't deliver any data.
Tested with Rainmeter 4.2 r3064 and Chrome 66 / Firefox 58.

Google Play Music, Soundcloud, Spotify and Youtube work properly.

**Comment by tjhrulz** [comment]
I know Twitch support needs reworked with their new sure layout but I have been to busy for that.
I'll look into Amazon Music and figure out what is up though.

**Comment by ceylon23** [comment]
I can confirm Amazon Music works with Rainmeter 4.1 Final Release r2989.

**Comment by Dudebaker** [comment]
I've now tested it again with your example v0.4.
Twitch does only work if I activate generic support but even then all metadata options return only "twitch" and the bangs do not really work.
Amazon Music doesn't return anything with or without generic support.

Rainmeter 4.2 final
Chrome 68.0.3440.75
Firefox 61.0.1

As my other (closed) issue I've tested this in a fresh Win10 VM too to see if this issue relates to my windows installation... but it's the same, the issue persists.

**Comment by tjhrulz** [comment]
Twitch I actually removed support for when their new website hit, that is why generic is taking over. I plan on having a new update work support added back as well as YouTube Music support.

As for Amazon Music what is your url when you access it and is it in a non English language?

**Comment by Dudebaker** [comment]
Ok then is the Twitch behavior currently intended.

As for Amazon Music, here's a example URL:
https://music.amazon.de/playlists/B07FXTGT1D

![image](https://user-images.githubusercontent.com/2338122/43532982-070c1a6c-95b4-11e8-8a01-ba6f2b899738.png)

I can only change the language over Sidebar -> Your Name -> Change Display Language.
But even with English it doesn't work.

If I want to change the URL to music.amazon.com it will let me login but immediately after this it redirect me to music.amazon.de.

**Comment by Dudebaker** [comment]
I've installed now a fresh Win10 VM in English.
But the issue persists.
Even if the system language is in English and the Site-Language was set to English, it will not display anything.

As before, I cannot use music.amazon.com since amazon redirects me to music.amazon.de (would bet for licence issues with multiple countries).

**Comment by tjhrulz** [comment]
Oh hey that is probably went it is not working your Amazon music, since it ends in .de the script will not be injected. I'll fix that today and we can see if the issue is resolved once it is inject, if not we can see what else is blocking it

**Comment by thechosen2k** [comment]
@tjhrulz I have the same problem with amazon.de - can you tell me how to update manually, i use the 0.40 release version

-so long

**Comment by tjhrulz** [comment]
Yeah it is not easy to fix it without manually whitelisting every single TLD, however I just pushed a patch that should fix it.

https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/b922a9c2e18f9d2d4bca10520010a341b3e03805

**Comment by chefbennyj1** [comment]
Hi there :) I can't seem to get music.amazon.ca to work.  I can see you've used a wild card ("*") for domain extensions in your code, but for some reason music.amazon still will not work with webnowplaying. I'd have to read the code to be sure... are you using XCopy to find the data in the html? is it possible they changed their layout?
