### ISSUE TITLE
SetPosition with Spotify or Soundcloud doesn't work

### ISSUE THREAD

**Issue by Dudebaker** [tjhrulz/WebNowPlaying#12]
**Integer-value:**
SetPosition <100 _and it jumps to 0% of the current track._
SetPosition >=100 _and it jumps to the next track._

**Double-value one decimal:**
SetPosition <= 9.9 _and it jumps to 0% of the current track._
SetPosition > 9.9 _and it jumps to the next track._

**Double-value two decimals:**
SetPosition <= 1.00 _and it jumps to 0% of the current track._
SetPosition > 1.00 _and it jumps to the next track._

It seems the dot in the double value gets terminated (I don't use double values anyway).

If you use double-values it will also jump to 0% with the Google Play Music or Youtube, otherwise the bang works properly with these two players.

Tested with Rainmeter 4.2 r3064 and Chrome 66 / Firefox 58.

**Comment by tjhrulz** [comment]
Is your plugin up to date? SetPosition is working just fine for me on those and it does properly support decimal

**Comment by Dudebaker** [comment]
I've now installed your example v0.4 and ticked the plugin to be sure it is the latest (but since it was not ticket it was the same).
As I saw there's already a SetPosition 50 bang on the AlbumArt Meter added to the example. A click on it and it jumps to the start of the current track and not to 50%.
If you change this "SetPosition 50" to "SetPosition 50.00" it will jump to the next track.
This only happens on Spotify and Soundcloud.

Completely the same behavior as in my own skin.

Rainmeter 4.2 final
Chrome 68.0.3440.75
Firefox 61.0.1

And now I've even tested this in a fresh Win7 and Win10 VM to see if this issue relates to my windows installation... but it's the same, the issue persists.
One note to the Win7 VM: Rainmeter crashes immediately after launch if a WebNowPlugin skin is loaded (yours or mine, doesn't matter).

The last thing I could think of is the language... I've set up all in german.

**Comment by tjhrulz** [comment]
Bet it's a language thing, I thought my mess should be language agnostic but I guess they must have changed something between the two.

**Comment by Dudebaker** [comment]
I have now installed a fresh Win10 VM in English.
The SetPosition Bang works properly with Soundcloud and Spotify.
A click on the AlbumArt Meter and it jumps to 50%.
Even if I change the Bang now to 50.00 it will jump to the correct 50% and not to the next track like before.

So this is really language related.
