### ISSUE TITLE
Google Play Music - Current Track Length Inaccurate

### ISSUE THREAD

**Issue by RafhaanShah** [tjhrulz/WebNowPlaying#15]
The current track position shows the total time since I started playing any album/playlist, not the current position in the currently playing track - see the screenshot attached. (Where it says 12:48 and 413%). 

![capture](https://user-images.githubusercontent.com/16906440/43038444-1d65ba0a-8d32-11e8-9daa-36044d5537cc.PNG)

**Comment by tjhrulz** [comment]
I know this used to be an issue however it seems google stopped being stupid on their end and it no longer does this
