### ISSUE TITLE
coding languge 

### ISSUE THREAD

**Issue by tarbear123** [tjhrulz/WebNowPlaying#16]
what coding languge do you guy use to create add-on's for programs

**Comment by tjhrulz** [comment]
Huh? Do you mean what language are plugins for Rainmeter written in? They are usual written in C++ or C# (Although anything that compiles to a dll could be used you would just want to port the API over)

A guide to making a plugin can be found here: https://docs.rainmeter.net/developers/plugin/plugin-anatomy/
