### ISSUE TITLE
installation is crazy (tidal not working)

### ISSUE THREAD

**Issue by chloeest** [tjhrulz/WebNowPlaying#20]
let me preface this... i am not very smart. 

i have tried installing manually, and automatically. ive even gotten it to the point where the Magick Album Art visualizer will show album covers when i play a song on soundcloud. But i cant get the monstercat visualizer to work with it, and i cant get it to work with tidal.

i've followed everything ive managed to find online, and am lost.

**Comment by tjhrulz** [comment]
Tidal might be broken, ill look into it.
