### ISSUE TITLE
Support for vk.com

### ISSUE THREAD

**Issue by NEONXSAMURAI** [tjhrulz/WebNowPlaying#21]
It would be great if this plugin could support VK music.
I know that VK is not at all popular in your country, but this is the most popular social network in Russia. Such as facebook in USA :)
https://vk.com

**Comment by tjhrulz** [comment]
Does this site actually support playing music though? I see no option for it.

**Comment by dein0s** [comment]
Yep, it does. But since it's a social network, you actually need to get an account first :)
![vk_music](https://i.imgur.com/wIMLskb.png)

**Comment by klezgt** [comment]
Hi, tjhrulz

Thanks a lot for your plugin,
I just came across with the same question as a DanyGee
VK.com support in your plugin would be so much appreciated!

thanks in advance.
