### ISSUE TITLE
Deezer not working. 

### ISSUE THREAD

**Issue by samofcoding** [tjhrulz/WebNowPlaying#26]
It works for youtube, soundcloud, and every other one I tried, but deezer won't have the ablum art appear.

**Comment by samofcoding** [comment]
I have added the firewall exception, and changed the allow HTTPS setting in about config. I am in firefox.

**Comment by tjhrulz** [comment]
Fixed, sadly support is less than perfect due to their volume and progress bars having goofy mouse events so neither Rainmeter bang will work with them
