### ISSUE TITLE
Could this be made to work with Waterfox?

### ISSUE THREAD

**Issue by Novadestin** [tjhrulz/WebNowPlaying#27]
When FireFox switched to web extensions, a lot of people "jumped ship" and moved to other browsers that still supported legacy addons, one of those being Waterfox - a forked version of FireFox. 

Given that there is already a companion addon for FireFox and that Waterfox is probably pretty similar, I was curious if a companion addon could be made for Waterfox as well (I can confirm it doesn't work with Waterfox 54.0.1).

Either way, thank you and keep up the great work!!

**Comment by tjhrulz** [comment]
Maybe, if "Waterfox" still ships with support for webextension then yes it will 100% work with it just like every other web browser that supports the web extension addon. While there is a "Chrome Companion" and a "Firefox Companion" the two code bases are 100% identical these days.

However if "Waterfox" does not support web extension then this extension does not and will not support that browser. Firefox gave more than enough warning that web extension were coming and they are much better and more secure than the older methods. While I wish they would have kept the old extensions around longer I understand keeping them working and secure (relatively speaking) was a very time consuming thing.
