### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by heqyoufree** [tjhrulz/WebNowPlaying#29]
The plugin takes up a lot of performance.
It Occupies CPU 10% to 80%.
I tried a lot of skins, but the problem still remains unresolved.

**Comment by tjhrulz** [comment]
Doubt it is related to this plugin it any way shape or form, this plugin is largely single threaded so there is no way it could use more than one core. 

Also there is nothing really intensive about this plugin (I have an outdated i5 4590 and attaching a debugger to Rainmeter a heavy skin uses sub 0.5%) it is more likely down to the skin/Rainmeter. I would recommend turning on GPU acceleration.
