### ISSUE TITLE
Firefox addon causes Error: Permission denied to object

### ISSUE THREAD

**Issue by Mikrz** [tjhrulz/WebNowPlaying#30]
I'm not sure of the cause, as I cannot find any reference to this function call in the source code, but it seems this addon somehow causes Firefox to make `window.onbeforeunload()` a "restricted function". This causes any calls to it to fail as "Error: Permission denied to access object"

This occurs on any website, and can be witnessed simply by trying to view the object or run the function in the browser console.

without the extension installed:
![image](https://user-images.githubusercontent.com/767190/59401404-935d6f00-8d68-11e9-9ebe-a2afebe79073.png)

with the extension installed:
![image](https://user-images.githubusercontent.com/767190/59401382-80e33580-8d68-11e9-8a3c-c65137dcd4fb.png)

This is on Windows 10 Insider Preview, using Firefox 67.0.1 with addon version 0.4.5.

**Comment by khanhas** [comment]
https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/blob/49d429f65c468037879f1637aea1ae42b683bcfb/WebNowPlaying.js#L632

**Comment by Mikrz** [comment]
Well thanks, not sure how it wasn't showing up in my searches. Either way, it seems by overriding this function in the addon that it basically breaks any website functionality that would want to use it. Drop.com for example. I have to completely disable or remove the addon to be able to navigate the site at all.
