### ISSUE TITLE
Stops working if I connect to VPN, even after I disconnect or restart browser+rainmeter

### ISSUE THREAD

**Issue by aminomancer** [tjhrulz/WebNowPlaying#31]
Windows 10 ver 1903
Firefox 69.0a1
Latest versions of rainmeter, webnowplaying.dll, and webnowplaying companion
The VPN is private internet access, latest version. When I connect, the plugin stops working. Even after disconnecting it still doesn't work. Of course the internet works fine, as do other internet-related plugins. This plugin is the only thing that stops working. The companion says "not connected, click to troubleshoot" which does nothing. Then if I reload rainmeter it *sometimes* throws an error in the log saying that there were problems loading the plugin or something. I can't remember exactly what it says, and the majority of the time it doesn't mention the plugin at all, it's just kinda failing but not throwing any errors. But at some point, the log said something like I can only define one of port/proxy/domain or something. I'm totally misremembering, but it was something like that. Like the VPN changed some type of network connection property which caused the plugin to fail, and thereafter the plugin just stops looking or something. The first time I noticed this I just restarted my computer and it worked fine after that. The second time I tried closing rainmeter and firefox, then disabling and re-enabling my network adapter. This also worked fine. But these aren't really good solutions, I feel like it shouldn't fail during a VPN connection at all, but if it must, it should be able to boot back up by just refreshing the skin or at least opening and closing rainmeter. It seems to have nothing to do with firefox, I reproduced the issue with chrome too. I also tried connecting to the VPN while firefox was closed, and then opening firefox. Same deal. It's like the plugin is listening for something that it shouldn't need to. I don't have any other VPN subscriptions so I can't test if this is true for any other VPN but I posted here so that users of other VPNs can test it out.

My temporary workaround is to create a second, identical layout, except this layout loads a different music player skin which looks the same, but which has no measures calling the plugin. That way if I connect to the VPN while this skin is loaded instead of my normal music player skin, then the plugin doesn't get loaded at all. And I can safely connect, disconnect, then switch to my normal skin, and webnowplaying initializes just fine. I'm not a huge fan of increasing the number of steps though. If I don't find a better solution to this then I will write a little autohotkey script to automatically switch layouts when I click the VPN tray icon. Still a very imperfect solution, since then I have to be careful not to click the tray icon but choose not to actually connect or disconnect. But the only alternative would be listening for network changes for a trigger, and then I don't think it will switch the layouts fast enough to have the plugin unloaded by the time it recognizes the network change that causes it to break. So really this is the kind of problem that calls for fixing the underlying issue, but I'm not sure if it's my VPN client, or the webnowplaying plugin. It seems like the plugin shouldn't care about my network connection at all though, so even if it is unique to my VPN client it seems like it's due to something unnecessary.

**Comment by tjhrulz** [comment]
I use a VPN with this just fine, I am going to guess that you may just be having issues with your VPN isolating certain programs to run on the VPN and others not while also adding a kill switch to airgap your connection, if that is the case there is nothing I can do about this.

This program entirely runs on localhost, so as long as no system is prevent connections over that there should be no issues, and if there is there is nothing I can do about that
