### ISSUE TITLE
Support for Mixcloud

### ISSUE THREAD

**Issue by DarkGhost7** [tjhrulz/WebNowPlaying#34]
I love this and use it for soundcloud and youtube, but noticed my rainmeter apps weren't working with https://www.mixcloud.com and notice that WNP doesn't support it. If you're free please add this site! :D Thanks and love the WNP functionality keep up the good work!

**Comment by tjhrulz** [comment]
I'll see if I can get around to it one of these days. I've been pretty busy with IRL stuff so I I make no promises on timeline and if you or someone else who uses the site and is a programmer wants to add it and submit a pull request before I get around to it feel free to
