### ISSUE TITLE
Youtube shuffle broken?

### ISSUE THREAD

**Issue by X-Anonymous-Y** [tjhrulz/WebNowPlaying#37]
Rainmeter 4.4.0.3338 beta (64-bit)
Language: German (1031)
Build time: 2019-11-19  7:55:40
Commit Hash: ab72019a
Windows 10 Pro 1909 64-bit (build 18363) - German (1031)
Path: C:\Program Files\Rainmeter\
SkinPath: D:\Daten\*\Rainmeter\Skins\
SettingsPath: C:\Users\*\AppData\Roaming\Rainmeter\
IniFile: C:\Users\*\AppData\Roaming\Rainmeter\Rainmeter.ini

and the same with the "4.3.1 Final Release"

Browser: Brave "Chromium: 79.0.3945.88 (Official Build) (64-bit)"
Chrome Extensions: WebNowPlaying "0.4.7"

I always get this error.

Protocol:
NOTE (15:21:06.492) WebNowPlayingExample\Example.ini: Refreshing skin
ERRO (15:21:07.506) : WebNowPlaing.dll - Error converting volume to integer, volume was:57.5144564799235
ERRO (15:21:07.517) : Web Side Error:Error updating shuffle for Youtube
ERRO (15:21:08.505) : Web Side Error:Error updating shuffle for Youtube
ERRO (15:21:09.505) : Web Side Error:Error updating shuffle for Youtube
ERRO (15:21:10.505) : Web Side Error:Error updating shuffle for Youtube

Debug Protocol:
DBUG (15:09:40.631) WebNowPlayingExample\Example.ini: Reading file: D:\Daten\*\Rainmeter\Skins\WebNowPlayingExample\Example.ini
DBUG (15:09:40.635) : Reading file: C:\Users\*\AppData\Roaming\Rainmeter\Rainmeter.ini
DBUG (15:09:44.518) : System.OverflowException: Der Wert für einen Int16 war zu groß oder zu klein. ---> System.OverflowException: Der Wert für einen Int32 war zu groß oder zu klein.

   bei System.Decimal.ToInt32(Decimal d)

   bei System.Decimal.ToInt16(Decimal value)

   --- Ende der internen Ausnahmestapelüberwachung ---

   bei System.Decimal.ToInt16(Decimal value)

   bei WebNowPlaying.Measure.WebNowPlaying.OnMessage(MessageEventArgs arg)
DBUG (15:09:44.539) : Web Error:TypeError: Cannot read property 'getAttribute' of undefined
DBUG (15:09:45.517) : Web Error:TypeError: Cannot read property 'getAttribute' of undefined
DBUG (15:09:46.514) : Web Error:TypeError: Cannot read property 'getAttribute' of undefined
DBUG (15:09:47.519) : Web Error:TypeError: Cannot read property 'getAttribute' of undefined

**Comment by tjhrulz** [comment]
Looks like youtube broke something with shuffle again (Possibly just in German), expect an update to fix it sometime in the middle of this week.
