### ISSUE TITLE
API besides rainmeter?

### ISSUE THREAD

**Issue by Akrasia** [tjhrulz/WebNowPlaying#4]
Any way I could interface with your plugin using Python or have the plugin simply output now playing info to text?

**Comment by BanjerHD** [comment]
I would love to see this possible too :)

**Comment by tjhrulz** [comment]
Sorry I thought I had responded to this before but I guess I half wrote my response and did not finish.

Sure you could easily hook up to the extension, you just need to be able to run a websocket server similar to how the Rainmeter plugin does it. However I make no promises that an update will not add new options to handle or change some other small feature internally.
Now if you don't want to have to deal with making a websocket server or you want to also keep the original plugin in tact that then I would recommend that you make a rainmeter skin to do the interfacing and have it send the info to python or saves it to a text file for you.
