### ISSUE TITLE
YouTube Issue

### ISSUE THREAD

**Issue by MiruE17** [tjhrulz/WebNowPlaying#41]
The skin didn't respond when I playing some music from Youtube. But the skin is still respond to soundcloud. Either the skin example and my edited skin had this same problem. This happen when I playing both the Mix and a single song/vid in youtube.
![image](https://user-images.githubusercontent.com/62545712/77309394-292e1d80-6d2f-11ea-8252-40e644c8267a.png)
This is what I used :
![image](https://user-images.githubusercontent.com/62545712/77309561-73170380-6d2f-11ea-9df0-17212f476822.png)
I also used the 0.4.7 version of the Companion

**Comment by aminomancer** [comment]
try my fork (on my page), then lmk if you get any errors or log messages in either rainmeter's log or browser's

**Comment by tjhrulz** [comment]
If service are broken please open the issue on the extension not the plugin: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues
