### ISSUE TITLE
Soundcloud album art no longer working

### ISSUE THREAD

**Issue by trevor-pope** [tjhrulz/WebNowPlaying#42]
OS: Windows 10
Rainmeter Version: 4.3.1.3321 (64-bit)
I am using the most recent version of the plugin.

When using Soundcloud, the track and artist name still works, but the album art no longer shows up. YouTube works just fine. This breaks in both the example skin and in the Monstercat Visualizer. In the Rainmeter log you get something along the lines of
> Unable to get album art from: https://i1.sndcdn.com/artworks-gv6BU6dXdgHcyD8y-sCsKrA-t500x500.jpg

though the URL is valid and works fine in browser. This happened recently, as I believe it was working just a month or two ago, so it may be a change with whatever Soundcloud API the Extension uses, or it might be an issue with the Rainmeter plugin breaking due to a Rainmeter update.

**Comment by clj3100** [comment]
Looks like a SSL issue as when the debug mode is on it logs this:

> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at WebNowPlaying.Measure.GetImageFromUrl(String id, String url)
> Unable to get album art from: https://i1.sndcdn.com/artworks-7NG1CtyfnM0etJjk-yV6Pag-t500x500.jpg

**Comment by tjhrulz** [comment]
If service are broken please open the issue on the extension not the plugin: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues

I have already fixed this issue there
