### ISSUE TITLE
Cleartext stuck at fetching... and exampleskin shows N/A

### ISSUE THREAD

**Issue by jenduis** [tjhrulz/WebNowPlaying#43]
Although plugin says "Connected and sending info" neither Cleartext nor WebNowPlayingExample works.

Yes i did the firewall thing.

And i'm using brave browser if it's important

**Comment by tjhrulz** [comment]
If it is connected and is not working then it is possible that the music service you are using the extension was not working to decode at the time. When services are broken please open the issue on the extension not the plugin and be sure to mention the service. Likely it has already been fixed https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues
