### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by trevor-pope** [tjhrulz/WebNowPlaying#45]
I am trying to build the project from source. I am using Visual Studio 2019, on Windows 10.

I cloned the repo and added my api keys, but I get the following error:
`syntax error at token '-' in:     IL_0029:  ldc.r8     -inf`

Is this an issue with ILMerge?

**Comment by tjhrulz** [comment]
Without having more info it is tough to say, make sure you are capable of building a C# Rainmeter extension from the examples Rainmeter provides. Likely you are missing to requisite for building Rainmeter extensions or have a bad copy of ILMerge

**Comment by tjhrulz** [comment]
So I find this funny that I stumbled upon this issue again, I figured out the cause. It is ilmerge being a pain and not liking my  Newtonsoft.Json library. As to why it worked on my old dev machine and not on your machine/my machine after reinstalling windows 🤷 

Regardless it should build always now, but as for my plugins that needed that library well that should be fun whenever I need to update one of them
