### ISSUE TITLE
Cleartext not fetching music from spotify

### ISSUE THREAD

**Issue by Razer323** [tjhrulz/WebNowPlaying#46]
i use the spotify web player and its not loading on the latest version of either webnowplaying or cleartext 
Not sure which one it is

**Comment by Skywalkr08** [comment]
Same here. Works with Youtube though

**Comment by Gamerbiomek2** [comment]
It works on the Spotify desktop version, he got rid of the web version because of the updates kept breaking the extension.

**Comment by tjhrulz** [comment]
If service are broken please open the issue on the extension not the plugin: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues
