### ISSUE TITLE
Support for Deezer

### ISSUE THREAD

**Issue by german95n** [tjhrulz/WebNowPlaying#5]
It would be greate if this plugin could support deezer:

http://deezer.com/

**Comment by tjhrulz** [comment]
This is already on my list of sites to support :P I have been busy though lately with various other improvements to Rainmeter. I probably will get to them all in a week or two I would say. I will leave this open till then.

**Comment by german95n** [comment]
Perfect! Happy to learn that ppl use Deezer too ^^

**Comment by tjhrulz** [comment]
Fully added as of https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/45a3a0d93af888319c5aaacc1db30123b3428f61

Should be in the update I have planned for this weekend.
