### ISSUE TITLE
WebnowPlaying Plugin not retrieving Youtube Information. 

### ISSUE THREAD

**Issue by SawuPogU** [tjhrulz/WebNowPlaying#53]
So I'm new to monstercat visualizer and I have it set up for Spotify music to be retrieved. But I want to listen to youtube music and have it shown through the visualizer. I have the plug-in installed and have the visualizer set to WebNowPlaying, but it is not being shown. Any help would be greatly appreciated.

**Comment by tjhrulz** [comment]
This is currently working and this issue is in the wrong repo
