### ISSUE TITLE
"does not exist or is not a valid path" can you help me, i just created acc for this

### ISSUE THREAD

**Issue by Frank-sys486** [tjhrulz/WebNowPlaying#55]
PS C:\Users\IKAW> spicetify backup apply spicetify v1.1.0 error C:\Users\IKAW\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.

**Comment by Frank-sys486** [comment]
uhh I guess I fixed it

i copied the path from the error
make folder
and
i copied the pref file (original file path)
`"C:\Users\user\LOCALS~1\APPLIC~1\APPLIC~1\APPLIC~1\APPLIC~1\APPLIC~1\APPLIC~1\APPLIC~1\APPLIC~1\APPLIC~1\APPLIC~1\Packages\SPOTIF~1.SPO\LOCALS~1\Spotify"
`then paste it in file (the file path is from error)
then enter the last command 
tada it work, then i paste it to an original file path

**Comment by tjhrulz** [comment]
This seems to be an issue with a skin being poorly written and pointing to the wrong place, I would contact the skin dev.
