### ISSUE TITLE
incorrect album artwork displayed when playing local songs via spotify

### ISSUE THREAD

**Issue by edor-1** [tjhrulz/WebNowPlaying#56]
I'm using the Monstercat visualizer in combination with webnowplaying via Spicetify. I use the album artwork feature, im having one issue with it. Any songs on Spotify I've added via local files don't display their artwork there, it just keeps the same artwork as the previous track/album i was listening to. Is there any way to fix this or make the album artwork part of the visualizer disappear temporarily whilst a song like this is playing? Its really nitpicky but it is annoying.

(Yes, the album artwork is embedded into the local files's metadata)

**Comment by khanhas** [comment]
Local file is not supported by spicetify, sorry. This is not Monstercat issue.
