### ISSUE TITLE
Support for Plex.tv

### ISSUE THREAD

**Issue by Gamerbiomek2** [tjhrulz/WebNowPlaying#6]
it would be great if this plugin could support Plex.tv

**Comment by tjhrulz** [comment]
I have added it to my list of players to investigate adding support for with the rewrite.

**Comment by tjhrulz** [comment]
Added with https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/0d521110fcbc5dd0f0d1dda53c97ed80136d4d03

Man did they make their site a pain to support. Only added music support for now, I will revisit later adding video support.
