### ISSUE TITLE
Apple Music Web Player Not Supported?

### ISSUE THREAD

**Issue by huckle1081** [tjhrulz/WebNowPlaying#61]
I'm using firefox and have the extension installed. It works properly with youtube, iTunes, and Spotify, but displays NA when I try to use Apple Music. I added the site to the extension whitelist and still nothing. Has anyone gotten it to work with Apple Music? Am I missing something?

**Comment by tjhrulz** [comment]
Support for apple music was added but was not pushed to live at the time you opened this issue. I believe it should be fully functional but I do not personally have access to apple music as I do not own any apple devices and borrowed a friends account to add support.

If it is still not working please open an issue under the extension not the plugin at https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues
