### ISSUE TITLE
Amazon Music broken with new layout on music.amazon.*

### ISSUE THREAD

**Issue by chefbennyj1** [tjhrulz/WebNowPlaying#62]
Hi there :) I can't seem to get music.amazon.ca to work. I can see you've used a wild card ("*") for domain extensions in your code, but for some reason music.amazon still will not work with webnowplaying. I'd have to read the code to be sure... are you using XPath to find the data in the html? 

I'm pretty sure it is because Amazon changed their layout :)

**Comment by tjhrulz** [comment]
This is an issue with the extension not with the plugin, this also has now been fixed but not pushed to live.
