### ISSUE TITLE
Not working in Spotify on Google Chrome

### ISSUE THREAD

**Issue by Taishi0228** [tjhrulz/WebNowPlaying#63]
It was working fine with the Rainmeter skin UnPlayer until several days ago, but the Rainmeter skin shows "N/A" when I play Spotify on Google Chrome. I have tried reinstalling the skin and WebNowPlaying, restarting my PC, and clearing the Google Chrome cache, but the problem persists.
There's no problem with playing Youtube and Deezer.

**Comment by Crissomar** [comment]
same here

**Comment by Migeru27** [comment]
The same also persists on firefox as well perhaps its spotify's API either making changes or disabling certain parts of their API
