### ISSUE TITLE
Suggestion: Get YouTube video date?

### ISSUE THREAD

**Issue by Cariboudjan** [tjhrulz/WebNowPlaying#65]
Possible to implement an option to get a video's release date? Handy for when listening to tech videos/podcasts and the news. The year would be able to tell me if what I'm listening to is relevant or outdated information by months/years/etc.

Example:
![image](https://user-images.githubusercontent.com/75376803/116966367-383f0900-ac6d-11eb-96bf-672fad7381fb.png)

**Comment by tjhrulz** [comment]
While a cool idea, YouTube is just about the only service that we would be able to add support for this too, couple that with how few skins supported release date/year with the old now playing plugins I just feel there is little point in adding support for this.
