### ISSUE TITLE
can we get an extension for Open Broadcast Software

### ISSUE THREAD

**Issue by Gamerbiomek2** [tjhrulz/WebNowPlaying#7]
I've been wanting to show the Artist/Song text with Open Broadcast Software Studio, so that I can show it on stream. That would be nice if you could do that

**Comment by tjhrulz** [comment]
I don't know if you saw it but I am currently exploring making a twitch overlay that will interface with the extension.

It may be a while before I get around to it but it is something I have thought about.

**Comment by Gamerbiomek2** [comment]
i didnt see it, but that sounds really cool and I can wait

**Comment by BNMotive** [comment]
this is such a fantastic program, I would love to hear an update.

**Comment by BNMotive** [comment]
this is such a fantastic program, I would love to hear an update. would it be possible to get the text file source for now?

**Comment by keifufu** [comment]
@tjhrulz and I discussed this yesterday. The plan is for the extension to be able to connect to multiple programs/websockets. This allows for rainmeter to work, in addition with being able to make adapters for things like outputting it to a file, displaying it in OBS, etc.

**Comment by keifufu** [comment]
The [new extension](https://github.com/keifufu/WebNowPlaying-Redux) will soon allow connecting to multiple adapters. 
For anyone interested, read [CreatingAdapters.md](https://github.com/keifufu/WebNowPlaying-Redux/blob/main/CreatingAdapters.md)
