### ISSUE TITLE
Web Side Error for Twitch

### ISSUE THREAD

**Issue by Gamerbiomek2** [tjhrulz/WebNowPlaying#71]
I opened the log in rainmeter and found a web side error for Twitch
![Webisde Error for Twitch](https://user-images.githubusercontent.com/22333494/125152938-671aa500-e11e-11eb-94e5-fb0ccce22772.png)

**Comment by keifufu** [comment]
Will be fixed on the official chrome/firefox extensions soon, but for now refer to [this repo](https://github.com/keifufu/WebNowPlaying-Redux)
