### ISSUE TITLE
WebNowPlaying has issues fetching data.

### ISSUE THREAD

**Issue by Gastymask** [tjhrulz/WebNowPlaying#72]
Could someone help me out with this issue I'm having? It seems like my WebNowPlaying is having issues fetching data for that are usually displayed over the album art. Any advice would be appreciated. Thanks!

![image](https://user-images.githubusercontent.com/88552299/128540647-4abc7d3a-cada-4fb2-8c77-2731e4204b3f.png)
![Screenshot (4)](https://user-images.githubusercontent.com/88552299/128540856-70201feb-f539-462e-b14c-88c14c8e7849.png)

**Comment by keifufu** [comment]
Going to close this for now as there hasn't been any activity and the error isn't very helpful.
Please try [this](https://github.com/keifufu/WebNowPlaying-Redux) extension for now, if it still doesn't work please open another Issue over there.
