### ISSUE TITLE
Return timestamp (number) representation of Position,Duration besides String

### ISSUE THREAD

**Issue by kenkangxgwe** [tjhrulz/WebNowPlaying#74]
Return a number representation of Position and Duration for `[MeasurePosition:]` according to https://docs.rainmeter.net/manual/variables/section-variables/#Colon.

This will be useful to 
1. calculate the remaining time: `([MeasureDuration:] - [MeasurePosition:])`.
2. customize the format by UpTime Measure: https://docs.rainmeter.net/manual/measures/uptime/#SecondsValue.

**Comment by tjhrulz** [comment]
The plugin does already return the number value as well as string value for both position and duration and that value is in seconds. It may be that section variables were not working with the plugin when you made this as I know there was a bug a while back. You also can use a calc measure to get the number value from the measure if section variables do not wrk.
