### ISSUE TITLE
Stopped working for Spicetify 2.8.5

### ISSUE THREAD

**Issue by momiji-oroshi** [tjhrulz/WebNowPlaying#78]
Now all of my rainmeter skins using this plugin cannot fetch the data like cover art or song names.

**Comment by uzervlad** [comment]
https://github.com/spicetify/spicetify-cli/issues/1514

**Comment by keifufu** [comment]
Make sure you have the browser extension installed, if you do and it's still broken please move to [this](https://github.com/keifufu/WebNowPlaying-Redux) extension for now.
