### ISSUE TITLE
404 again

### ISSUE THREAD

**Issue by plutonium-239** [tjhrulz/WebNowPlaying#80]
:/
Looks like the chrome web store page is doing it again.

**Comment by Goku-04** [comment]
Same

**Comment by designerfarag** [comment]
Also having this issue, hope it can get fixed soon!

**Comment by Goku-04** [comment]
well for now I downloaded the extension source code and loaded it unpacked in edge after turning on developer mode and it worked just fine
[WebNowPlaying Source Code](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension)
https://github.com/tjhrulz/WebNowPlaying-BrowserExtension
![image](https://user-images.githubusercontent.com/65329453/159121726-42eee13c-491c-4f0d-9d2d-5278851f2ed6.png)

**Comment by designerfarag** [comment]
Looks like it's back up! You can probably close this. 

[Web Link Working](https://chrome.google.com/webstore/detail/webnowplaying-companion/jfakgfcdgpghbbefmdfjkbdlibjgnbli)
