### ISSUE TITLE
YouTube Music Progress Incorrectly Captured

### ISSUE THREAD

**Issue by haruki-taka8** [tjhrulz/WebNowPlaying#81]
Under unknown circumstances on YouTube Music, `PlayerType=Position` occasionally provides the required timestamp, but with a leading newline and four spaces.

Example:
```
[Measure.Position]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Position
```

returns the string

```

    1:23
```

and, as expected, the number `83`.

---

This can be temporarily fixed on the Rainmeter side by appending these two lines under the measure.

```
RegexpSubstitute=1
Substitute="\n    ":""
```

---

Environment:
* Windows 10 x64, build 19044
* Rainmeter 4.5.12.3616
* WebNowPlaying.dll 0.5.0.0
* WebNowPlaying Companion 0.5.0
* Brave 1.36.112 (Chromium 99.0.4844.51)

**Comment by haruki-taka8** [comment]
According to my hello-world-level experience in C# and OOP in general, changing the following line may fix the issue.

|Old|New|
|----|-----|
|https://github.com/tjhrulz/WebNowPlaying/blob/905303b98ba2c7c4b46e5c1532e20c0ab8a51d1f/WebNowPlaying.cs#L231|`currMusicInfo.Position = info.Trim();`|

**Comment by keifufu** [comment]
Fixed in [this](https://github.com/keifufu/WebNowPlaying-Redux) browser extension for now, will be fixed in the official one soon too.
