### ISSUE TITLE
Artist doesn´t show on Spotify Web Player

### ISSUE THREAD

**Issue by dreamazeV** [tjhrulz/WebNowPlaying#82]
I cannot make it work

**Comment by jweled** [comment]
I have this issue as well. I checked the error log and it constantly fails to update the state, repeat and volume.
![image](https://user-images.githubusercontent.com/79212970/176016977-6bae09fc-520f-4a64-a764-14f3631476d7.png)

**Comment by antonysze** [comment]
I have same issue

**Comment by keifufu** [comment]
Fixed in [this](https://github.com/keifufu/WebNowPlaying-Redux) version of the browser extension for now. Will also be fixed on the official one soon.
