### ISSUE TITLE
Web Side Error

### ISSUE THREAD

**Issue by radiotransparent** [tjhrulz/WebNowPlaying#83]
I'm using "attempt to support websites using generic script" on a streaming website.  Everything works as expected in Monstercat Visualizer.  I am receiving a lot of errors in the Rainmeter log, though:

![image](https://user-images.githubusercontent.com/29668378/188760949-d803d5b6-9695-4889-8dc5-93a0e47eb46b.png)

It would be great if this could be fixed @tjhrulz.   Thanks.

**Comment by mininmobile** [comment]
getting the same problem for spotify web player with updating `repeat`, `volume`, and `state`

**Comment by Nariod14** [comment]
Having the same thing whenever I watch Twitch. Here's an image. I feel this may be a memory leak or something since its always checking uselessly. 
![image](https://user-images.githubusercontent.com/21109756/198352962-67923811-69b9-40f4-9fc3-a9825836f5a5.png)

**Comment by keifufu** [comment]
Will be fixed on the official chrome/firefox extensions soon, but for now refer to [this repo](https://github.com/keifufu/WebNowPlaying-Redux)
