### ISSUE TITLE
[Crticial] Error on not supported Twitch site.

### ISSUE THREAD

**Issue by CrazyWolf13** [tjhrulz/WebNowPlaying#86]
Please make the Twitch website work:

As album cover art: Twitch channel cover
As song name: stream name
as artist name: streamer and current "game"

**Comment by CrazyWolf13** [comment]
@tjhrulz

**Comment by CrazyWolf13** [comment]
![image](https://user-images.githubusercontent.com/96661824/211052851-8b0d397d-284a-4275-82b0-9f385be98bb1.png)
Now i know why Rainmeter is using 25% CPU load.
Hope for a quick fix thank you @tjhrulz

**Comment by CrazyWolf13** [comment]
Possibel duplicate of #83

**Comment by keifufu** [comment]
Will be fixed on the official chrome/firefox extensions soon, but for now refer to [this repo](https://github.com/keifufu/WebNowPlaying-Redux)
