### ISSUE TITLE
Date and time format

### ISSUE THREAD

**Issue by beyenilmez** [tjhrulz/WebNowPlaying#89]
Plugin doesn't work on Turkish date/time format. But it works on English.

**Comment by keifufu** [comment]
What exactly is broken? If it's the volume control, that's fixed in [this](https://github.com/keifufu/WebNowPlaying-Redux) extension, and will also be fixed here soon.

**Comment by keifufu** [comment]
Most likely fixed in the new version [here](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter)
