### ISSUE TITLE
last.fm

### ISSUE THREAD

**Issue by Botanistt** [tjhrulz/WebNowPlaying#9]
Could you add last.fm support?

**Comment by tjhrulz** [comment]
Last.fm's webplayer is still just a spotify wrapper, just install the Spotify desktop plugin since it still plays through that.

**Comment by Botanistt** [comment]
Actually that is a false statement. I often listen using soundcloud, youtube or AIMP4 player. Occasionally Spotify. All these platforms support last.fm scrobbling and because of that I can keep track of music I listen to. There is no way I can display the title of songs I listen to because Rainmeter lacks support for all these platforms and this was the only possible way how to make it happen. I am more than sure I am not the only one in such situation. If you already have made your mind about not implementing last.fm support, I guess there is nothing else I can do towards this matter.

Sinceraly, 
Botanistt

**Comment by tjhrulz** [comment]
You mean the web player at the top right? In my experience scrobles don't show up there, only content from Spotify. Care to tell me how to play something else so I can actually add support then?

**Comment by Botanistt** [comment]
No, not the web player at the top.
So here is my profile link (just for an example) https://www.last.fm/user/wueue and as you can see it stores the information about songs I have been listening to. It works with dozens of platforms: media players, youtube, soundcloud, spotify, etc. Basically stores it in one place.
You can get the information about now playing songs using their API.
You don't play music using the last.fm. I mean, you can do that but it is not necessary.  You use scrobbler extension and listen to your music just like you would normally do it. I hope you got the idea.

**Comment by tjhrulz** [comment]
Then every single source you mentioned this extension already supports and you are good to go.

**Comment by Botanistt** [comment]
So you are saying it would work with all of them at once?

This would require to use additional extension. If last.fm was supported it wouldn't be necessary for additional one. Besides the support of scrobbling is enormous. Here is just a half of possibilities https://pastebin.com/vAd5us91
Either way, this is just a suggestion.

**Comment by tjhrulz** [comment]
Even if I were to add support for Last.fm it would still require the same extension it would to support all the other sites.

Also the last.fm API does not have near the feature set that my extension has as their API only gives you the info and nothing about the state or position, it also does not let you manipulate what is playing either. If you want support for another web based player on that list all you have to do is ask I will gladly add support when I can get around to it.
